In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os

In [2]:
H_P1 = pd.read_csv("Data//Original_Data//HarrisPartI.csv")          
H_P2 = pd.read_csv("Data//Original_Data//HarrisPartII.csv")         
H_P3 = pd.read_csv("Data//Original_Data//HarrisPartIII.csv")        
V_T2 = pd.read_csv("Data//Original_Data//vandenBerg_table2.csv")        
K_21 = pd.read_csv("Data//Original_Data//Krause21.csv")

In [8]:
H_P1[["ID","Name"]]

            ID    Name
0      NGC 104  47 Tuc
1      NGC 288     NaN
2      NGC 362     NaN
3    Whiting 1     NaN
4     NGC 1261     NaN
..         ...     ...
152   NGC 7089     M 2
153   NGC 7099    M 30
154     Pal 12     NaN
155     Pal 13     NaN
156   NGC 7492     NaN

[157 rows x 2 columns]

In [12]:
V_T2[["#NGC","Name"]]

    #NGC   Name
0    104  47Tuc
1    288   XXXX
2    362   XXXX
3   1261   XXXX
4   1851   XXXX
5   2808   XXXX
6   3201   XXXX
7   4147   XXXX
8   4590    M68
9   4833   XXXX
10  5024    M53
11  5053   XXXX
12  5272     M3
13  5286   XXXX
14  5466   XXXX
15  5904     M5
16  5927   XXXX
17  5986   XXXX
18  6101   XXXX
19  6121     M4
20  6144   XXXX
21  6171   M107
22  6205    M13
23  6218    M12
24  6254    M10
25  6304   XXXX
26  6341    M92
27  6352   XXXX
28  6362   XXXX
29  6366   XXXX
30  6397   XXXX
31  6496   XXXX
32  6535   XXXX
33  6541   XXXX
34  6584   XXXX
35  6624   XXXX
36  6637    M69
37  6652   XXXX
38  6656    M22
39  6681    M70
40  6715    M54
41  6717   XXXX
42  6723   XXXX
43  6752   XXXX
44  6779    M56
45  6809    M55
46  6838    M71
47  6934   XXXX
48  6981    M72
49  7078    M15
50  7089     M2
51  7099    M30
52  XXXX  Arp21
53  XXXX  Pal12
54  XXXX   Ter8

In [15]:
K_21[["Object","AltName"]]

         Object     AltName
0        NGC104       47Tuc
1        NGC288    Melotte3
2        NGC362    Dunlop62
3       NGC1261  Caldwell87
4       NGC1851   Dunlop508
..          ...         ...
56      NGC7089          M2
57      NGC7099         M30
58  Ruprecht106        NONE
59      Terzan7        NONE
60    Palomar12        NONE

[61 rows x 2 columns]

In [18]:
H_P1 = pd.read_csv("Data//Standardised_IDs//HarrisPartI.csv")          
H_P2 = pd.read_csv("Data//Standardised_IDs//HarrisPartII.csv")         
H_P3 = pd.read_csv("Data//Standardised_IDs//HarrisPartIII.csv")        
V_T2 = pd.read_csv("Data//Standardised_IDs//vandenBerg_table2.csv")        
K_21 = pd.read_csv("Data//Standardised_IDs//Krause21.csv")

In [22]:
K_21[["ID","Name"]]

         ID        Name
0    NGC104       47Tuc
1    NGC288    Melotte3
2    NGC362    Dunlop62
3   NGC1261  Caldwell87
4   NGC1851   Dunlop508
..      ...         ...
56  NGC7089          M2
57  NGC7099         M30
58   Rup106        NONE
59  Terzan7        NONE
60    Pal12        NONE

[61 rows x 2 columns]